name: Build  Docker image

on:
  push:
    branches: main
 

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2


    -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      
   
    - 
      name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: viktorija23/mentalwellbeingrepo
        registry: docker.io
      
        tags: viktorija23/mentalwellbeingrepo:latest
        
         
